"""
Auto-generated by update_pipeline.py
Merges player_box_advanced_metrics + pbp_player_metrics
to create player_scouting_tournament68.csv (all 68 tournament teams).
"""
import sys
from pathlib import Path

import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from config import (
    PLAYER_BOX_ADVANCED,
    PBP_PLAYER_METRICS,
    TOURNAMENT_BRACKET,
    PLAYER_SCOUTING_68,
)

box = pd.read_csv(PLAYER_BOX_ADVANCED)
pbp = pd.read_csv(PBP_PLAYER_METRICS)
brkt = pd.read_csv(TOURNAMENT_BRACKET)

tourney_teams = set(brkt["team_location"].unique())

box_68 = box[box["team_location"].isin(tourney_teams)].copy()
print(f"Box metrics: {len(box_68)} players from {box_68['team_location'].nunique()} tournament teams")

merged = box_68.merge(pbp, on="athlete_id", how="left", suffixes=("", "_pbp"))

dup_cols = [c for c in merged.columns if c.endswith("_pbp")]
merged = merged.drop(columns=dup_cols)

PLAYER_SCOUTING_68.parent.mkdir(parents=True, exist_ok=True)
merged.to_csv(PLAYER_SCOUTING_68, index=False)
print(f"Written: {PLAYER_SCOUTING_68.name}  ({len(merged)} rows, {len(merged.columns)} cols)")
print(f"Teams with player data: {merged['team_location'].nunique()} / 68 tournament teams")
