"""
Auto-generated by update_pipeline.py
Merges player_box_advanced_metrics + pbp_player_metrics
to create player_scouting_tournament68.csv (all 68 tournament teams).
"""
import pandas as pd
from pathlib import Path
DATA_DIR = Path(__file__).parent

box  = pd.read_csv(DATA_DIR / "player_box_advanced_metrics.csv")
pbp  = pd.read_csv(DATA_DIR / "pbp_player_metrics.csv")
brkt = pd.read_csv(DATA_DIR / "tournament_bracket.csv")

tourney_teams = set(brkt["team_location"].unique())

box_68 = box[box["team_location"].isin(tourney_teams)].copy()
print(f"Box metrics: {len(box_68)} players from {box_68['team_location'].nunique()} tournament teams")

merged = box_68.merge(pbp, on="athlete_id", how="left", suffixes=("","_pbp"))

dup_cols = [c for c in merged.columns if c.endswith("_pbp")]
merged = merged.drop(columns=dup_cols)

out_path = DATA_DIR / "player_scouting_tournament68.csv"
merged.to_csv(out_path, index=False)
print(f"Written: {out_path.name}  ({len(merged)} rows, {len(merged.columns)} cols)")
print(f"Teams with player data: {merged['team_location'].nunique()} / 68 tournament teams")
